# Generated by Django 5.1.7 on 2025-03-07 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consultationslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationslot',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='consultationslot',
            name='every_two_weeks',
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='days_of_week',
            field=models.CharField(default='MO', max_length=20),
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='repeat_every',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='consultationslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
