# Generated by Django 5.1.7 on 2025-03-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_consultationslot_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('consultation_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultationslot')),
            ],
        ),
    ]
